### ISSUE TITLE
negative coordinates

### ISSUE THREAD

**Issue by lgelderloos** [ranjaykrishna/visual_genome_python_driver#21]
Several bounding box coordinates in region_descriptions.json file contain negative values for x and/or y. If I understand correctly, the x and y coordinates indicate the lower left corner with the origin at the lower left corner of the image, therefore should never be negative... I am using version 1.2 of the dataset.
I count 5,408,689 region descriptions (which, surprisingly, is more than 4,297,502 which is listed on the visual genome homepage), of which 5654 contain a negative coordinate. There are also cases like region 5456063, in which even y + height yields a negative.What should one do about these cases?

Some examples with large negative coordinates:
{'height': 25, 'x': 179, 'phrase': 'A cloud in the sky.', 'image_id': 2330845, 'region_id': 5851305, 'width': 55, 'y': -904}
{'height': 6, 'x': 216, 'phrase': 'A window on a building.', 'image_id': 2315874, 'region_id': 5455943, 'width': 8, 'y': -710}
{'height': 24, 'x': 181, 'phrase': 'A leaf on a stem.', 'image_id': 2315869, 'region_id': 5456063, 'width': 25, 'y': -871}

Some examples with small negative coordinates (more frequent):
{'height': 35, 'x': 480, 'phrase': 'glass window on the building', 'image_id': 2417220, 'region_id': 5503839, 'width': 10, 'y': -2}
{'x': 1, 'height': 70, 'phrase': 'white bowl behind plate', 'width': 277, 'image_id': 2417836, 'y': -1, 'region_id': 5514392}
{'x': -1, 'height': 327, 'phrase': 'white plate with food', 'width': 500, 'image_id': 2417836, 'y': 45, 'region_id': 5514399}
{'x': -1, 'height': 207, 'phrase': 'wooden blocks of tile covering floor', 'width': 498, 'image_id': 2417841, 'y': 291, 'region_id': 5514473}
{'x': 415, 'height': 327, 'phrase': 'telephone wire running up wall', 'width': 82, 'image_id': 2417841, 'y': -1, 'region_id': 5514478}

**Comment by ranjaykrishna** [comment]
Ah yes, that was an artifact of the annotation script we used. Any out of bounds indices should be rounded to the nearest edge of the image.
