### ISSUE TITLE
Getting common images between COCO and Visual Genome 

### ISSUE THREAD

**Issue by dbalaram** [ranjaykrishna/visual_genome_python_driver#25]
Hi, 

I was wondering how you determined the common images between COCO and Visual Genome. I need to use the common images for a project.  Is there a way to access these images on the website?

Thanks!

**Comment by ranjaykrishna** [comment]
We asked the MSCOCO authors for the images a long time ago. All images with a coco_id are common between the two datasets. Since the datasets have evolved over time, only 50% of Visual Genome is now part of MSCOCO.
