### ISSUE TITLE
"local.py" doesn't work

### ISSUE THREAD

**Issue by lijin-THU** [ranjaykrishna/visual_genome_python_driver#3]
Since `GetAllImageData()` uses `json.load()` as return value, `GetAllImageData()` will return a list of dictionary, not a list of `Image` object. Then the follow code in `GetAllRegionDescriptions()` and `GetAllQAs()` will not work:

``` python
imageData = GetAllImageData()
  imageMap = {}
  for d in imageData:
    imageMap[d.id] = d
```

because `d` is a dictionary, not a parsed image data, the `d.id` here will not work.

I think it's better to change the return value of  `GetAllImageData()` to a list of `Image` objects.

**Comment by lijin-THU** [comment]
Besides, the download files from the website have some problem.

The zipped file in `region_descriptions.json.zip` is `region_annotations.json`, not `region_descriptions.json`. And there is a `bad CRC 0beb241a  (should be 393e4fb8)` error when I unzip this file.

**Comment by ranjaykrishna** [comment]
Should be fixed now.
