### ISSUE TITLE
Matching images to COCO images and ids

### ISSUE THREAD

**Issue by twistedcubic** [ranjaykrishna/visual_genome_python_driver#30]
Hi @ranjaykrishna,

Great dataset. I am trying to match the Visual Genome images to the ones in COCO. Based on the meta data, 103077 images have a flickr_id, 51498 of which also have a coco_id. For the remaining 51579, I tried using their flickr_id to find the corresponding COCO id, but these flickr_ids do not appear in the COCO dataset, at least as far as the flickr_urls indicate.

Can you tell me how to find the COCO images/ids corresponding to the 51579 images that don't have a coco_id?

Thanks!

**Comment by ritwickchaudhry** [comment]
There's an answer in the closed Issues, suggesting that due to developments in both VG and MSCOCO, only around 50% of VG images are common to MSCOCO.

**Comment by ranjaykrishna** [comment]
@ritwickchaudhry is correct. Due to the divergences between the two datasets during development, there is now only a ~50% overlap between the images.
